name: Keep Strapi Alive

on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes
  workflow_dispatch: # Allows manual trigger if needed

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Strapi Admin
        run: curl -I https://peak-post-strapi.onrender.com/admin
